### ISSUE TITLE
Formatting doesn't match MD

### ISSUE THREAD

**Issue by Jmainguy** [Bandwidth/ap-docs#56]
The formatting of http://dev.bandwidth.com/ap-docs/methods/availableNumbers/postAvailableNumbersLocal.html does not match the MD. https://github.com/Bandwidth/ap-docs/blob/master/methods/availableNumbers/getAvailableNumbersLocal.md

On the live site, mandatory has only one * for localNumber and inLocalCallingArea.

But the MD has 3 ***'s

Further down where it explains what the *'s mean, on the live site, it does not match up, causing confusion.

**Comment by dtolb** [comment]
Got it, the *** is a `*` but bolded

**Comment by Jmainguy** [comment]
/me glances at http://dev.bandwidth.com/ap-docs/methods/availableNumbers/postAvailableNumbersLocal.html. Why did you decide to close this without a fix?

**Comment by dtolb** [comment]
https://github.com/Bandwidth/ap-docs/pull/77
